### ISSUE TITLE
テレポート処理を遅延させる

### ISSUE THREAD

**Issue by ghost** [AzisabaNetwork/LeonGunWar#11]
1人ずつ遅延させてテレポートすることによりラグを軽減する

**Comment by testusuke** [comment]
TP先で人が重なりラグが発生する問題を解決しました。

**Comment by testusuke** [comment]
TP処理の遅延についてはデバッグ中です。

**Comment by siloneco** [comment]
古すぎるのでクローズ  
まだこのIssueが必要な場合は再度Openしてください
