### ISSUE TITLE
チャットテンプレート機能の追加

### ISSUE THREAD

**Issue by ghost** [AzisabaNetwork/LeonGunWar#13]
## 説明
本を開いて文字をクリックすると定型文を送信する

## 引用元
![image](https://user-images.githubusercontent.com/33691365/70374459-cc505800-1935-11ea-8175-8d5c774a28f2.png)

**Comment by siloneco** [comment]
古すぎるのでクローズ  
まだこのIssueが必要な場合は再度Openしてください
