### ISSUE TITLE
Inventory_Controlを設定ファイルで管理する

### ISSUE THREAD

**Issue by ghost** [AzisabaNetwork/LeonGunWar#22]
Inventory_Controlをワールド単位でホワイトリスト/ブラックリストする設定ファイルを作り、それを読み込むシステムを作る。
現状ではコードに埋め込んでいるためスマートではない。

**Comment by YukiLeafX** [comment]
現状ではこの2ファイルを指す
- https://github.com/AzisabaNetwork/LeonGunWar/blob/develop/src/main/java/net/azisaba/lgw/core/listeners/others/DisableNormalWeaponsInNewYearPvE.java
- https://github.com/AzisabaNetwork/LeonGunWar/blob/develop/src/main/java/net/azisaba/lgw/core/listeners/others/DisableToysDuringMatchListener.java

**Comment by YukiLeafX** [comment]
1つのパッケージにまとめました
https://github.com/AzisabaNetwork/LeonGunWar/tree/develop/src/main/java/net/azisaba/lgw/core/listeners/weaponcontrols

**Comment by siloneco** [comment]
古すぎるのでクローズ  
まだこのIssueが必要な場合は再度Openしてください
